title: Zipei's Blog
author: Zipei Geng
theme: leap-day
email: zigeng@student.ethz.ch
description: > # this means to ignore newlines until "baseurl:"
  Thoughts of learning data science and machine learning.
  
# social links
twitter_username: ZipeiGeng # DO NOT include the @ character, or else the build will fail!
github_username:  zpgeng # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
